In [17]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# Liste der URLs f체r die drei Jahre
urls = [
    "https://raw.githubusercontent.com/RFankhauser/MSc_WI_BINA/refs/heads/main/Semesterarbeit/Wetter_Z%C3%BCrich_st%C3%BCndlich/ugz_ogd_meteo_h1_2022.csv",
    "https://raw.githubusercontent.com/RFankhauser/MSc_WI_BINA/refs/heads/main/Semesterarbeit/Wetter_Z%C3%BCrich_st%C3%BCndlich/ugz_ogd_meteo_h1_2023.csv",
    "https://raw.githubusercontent.com/RFankhauser/MSc_WI_BINA/refs/heads/main/Semesterarbeit/Wetter_Z%C3%BCrich_st%C3%BCndlich/ugz_ogd_meteo_h1_2024.csv"
]

# Alle Dateien einlesen und in einer Liste speichern
dataframes = []
for url in urls:
    df = pd.read_csv(url, sep=",", encoding="utf-8")
    dataframes.append(df)

# Alle DataFrames vertikal zusammenf체gen
df_all_wetter = pd.concat(dataframes, ignore_index=True)

# Datum in datetime konvertieren (korrekte Variable verwenden)
df_all_wetter["Datum"] = pd.to_datetime(df_all_wetter["Datum"], errors="coerce")

display(df_all_wetter.head(10))

,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,T,h1,gradcelsius,7.22,bereinigt
1,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,Hr,h1,relative_Luftfeuchtigkeit,82.93,bereinigt
2,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,p,h1,hPa,977.20,bereinigt
3,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
4,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,StrGlo,h1,W/m2,0.02,bereinigt
5,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,WD,h1,째,184.59,bereinigt
6,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,WVv,h1,m/s,1.04,bereinigt
7,2022-01-01 00:00:00+01:00,Zch_Stampfenbachstrasse,WVs,h1,m/s,1.16,bereinigt
8,2022-01-01 00:00:00+01:00,Zch_Schimmelstrasse,T,h1,gradcelsius,5.96,bereinigt
9,2022-01-01 00:00:00+01:00,Zch_Schimmelstrasse,Hr,h1,relative_Luftfeuchtigkeit,NaN,bereinigt

In [16]:

# NA-Werte in "Wert" mit NaN setzen, um korrekt zu mitteln
df_all_wetter["Wert"] = pd.to_numeric(df_all_wetter["Wert"], errors="coerce")

# Durchschnitt pro Stunde und Parameter berechnen
df_avg = df_all_wetter.groupby(["Datum", "Parameter"])["Wert"].mean().reset_index()

# Umstrukturieren der Tabelle: Spalten f체r die einzelnen Parameter
df_pivot_wetter = df_avg.pivot(index="Datum", columns="Parameter", values="Wert").reset_index()

# DataFrame anzeigen
display(df_pivot_wetter.head(10))

Parameter,Datum,Hr,RainDur,StrGlo,T,WD,WVs,WVv,p
0,2022-01-01 00:00:00+01:00,84.575,0.0,0.02,6.590000,182.530000,0.603333,0.390000,978.233333
1,2022-01-01 01:00:00+01:00,85.035,0.0,0.02,6.313333,167.976667,0.503333,0.376667,978.106667
2,2022-01-01 02:00:00+01:00,86.815,0.0,0.03,6.023333,243.186667,0.553333,0.286667,978.163333
3,2022-01-01 03:00:00+01:00,87.505,0.0,0.02,5.553333,171.720000,0.443333,0.210000,978.450000
4,2022-01-01 04:00:00+01:00,88.500,0.0,0.02,5.083333,214.436667,0.356667,0.230000,978.446667
5,2022-01-01 05:00:00+01:00,88.900,0.0,0.02,4.833333,63.666667,0.346667,0.250000,978.573333
6,2022-01-01 06:00:00+01:00,88.980,0.0,0.02,4.466667,143.230000,0.576667,0.625000,978.443333
7,2022-01-01 07:00:00+01:00,89.725,0.0,0.02,4.466667,73.110000,0.416667,0.115000,978.360000
8,2022-01-01 08:00:00+01:00,89.190,0.0,20.21,3.843333,151.373333,0.716667,0.620000,978.826667
9,2022-01-01 09:00:00+01:00,89.920,0.0,119.28,3.616667,236.896667,0.563333,0.503333,978.686667